apiVersion: v1
kind: Service
metadata:
  name: fruits-app
spec:
  selector:
    app: fruits-app
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruits-app
spec:
  selector:
    matchLabels:
      app: fruits-app
  template:
    metadata:
      labels:
        app: fruits-app
    spec:
      containers:
      - name: fruits-app
        image: rhdevelopers/fruits-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

